name: 04-Semantic Tests

on:
  workflow_run:
    workflows: ["03-AST Tests"]
    types:
      - completed
    branches: [main]
  workflow_dispatch:

jobs:
  semantic-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run semantic analysis tests
        run: |
          cd ~/MiniGo/src
          python main.py gen && clear
          rm -f ./test/testcases/* 2>/dev/null
          rm -f ./test/solutions/* 2>/dev/null
          python main.py test CheckSuite